# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - "https://www.paypal.com/donate/?business=paypal.mournful099@passinbox.com&item_name=RustBaas"
