//! Per-user TOTP secret storage.
//!
//! One row per user with TOTP enrolled. Lifecycle:
//!
//! - `enroll`           creates the row in pending state (enabled=0).
//!   The secret is generated by the caller (the API layer, via
//!   `totp_rs::Secret::generate_secret().to_encoded()`) and stored
//!   base32-encoded — the canonical wire format for authenticator
//!   apps and the URI scheme.
//! - `confirm_enabled`  flips enabled=1 after the user proves they
//!   programmed the secret correctly by submitting a fresh TOTP code.
//! - `disable`          removes the row outright. Re-enrolment goes
//!   through `enroll` again, which means a fresh secret + QR scan.

use crate::error::Result;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::SqlitePool;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow)]
pub struct UserTotp {
    pub user_id: String,
    pub secret_b32: String,
    pub enrolled_at: DateTime<Utc>,
    pub confirmed_at: Option<DateTime<Utc>>,
    pub enabled: bool,
}

/// Create or replace the user's pending TOTP enrolment. Any prior
/// row (pending or enabled) is overwritten — re-enrolment forces a
/// new secret + QR scan, which is the desired UX.
pub async fn enroll(pool: &SqlitePool, user_id: &str, secret_b32: &str) -> Result<UserTotp> {
    let now = Utc::now();
    sqlx::query(
        "INSERT INTO _user_totp (user_id, secret_b32, enrolled_at, confirmed_at, enabled) \
         VALUES (?, ?, ?, NULL, 0) \
         ON CONFLICT(user_id) DO UPDATE SET \
             secret_b32 = excluded.secret_b32, \
             enrolled_at = excluded.enrolled_at, \
             confirmed_at = NULL, \
             enabled = 0",
    )
    .bind(user_id)
    .bind(secret_b32)
    .bind(now)
    .execute(pool)
    .await?;
    Ok(UserTotp {
        user_id: user_id.into(),
        secret_b32: secret_b32.into(),
        enrolled_at: now,
        confirmed_at: None,
        enabled: false,
    })
}

pub async fn find(pool: &SqlitePool, user_id: &str) -> Result<Option<UserTotp>> {
    let row: Option<UserTotp> = sqlx::query_as(
        "SELECT user_id, secret_b32, enrolled_at, confirmed_at, \
                CAST(enabled AS BOOLEAN) AS enabled \
         FROM _user_totp WHERE user_id = ?",
    )
    .bind(user_id)
    .fetch_optional(pool)
    .await?;
    Ok(row)
}

/// Flip a pending enrolment to enabled. Returns the number of rows
/// affected — 0 means there was no pending row for this user.
pub async fn confirm_enabled(pool: &SqlitePool, user_id: &str) -> Result<u64> {
    let res = sqlx::query(
        "UPDATE _user_totp SET enabled = 1, confirmed_at = ? \
         WHERE user_id = ? AND enabled = 0",
    )
    .bind(Utc::now())
    .bind(user_id)
    .execute(pool)
    .await?;
    Ok(res.rows_affected())
}

/// Delete the user's TOTP row entirely. Idempotent.
pub async fn disable(pool: &SqlitePool, user_id: &str) -> Result<u64> {
    let res = sqlx::query("DELETE FROM _user_totp WHERE user_id = ?")
        .bind(user_id)
        .execute(pool)
        .await?;
    Ok(res.rows_affected())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::migrations::{APP_MIGRATIONS, apply_migrations};
    use crate::pool::open_memory_pool;
    use crate::users::insert_user;

    async fn fresh() -> (SqlitePool, String) {
        let pool = open_memory_pool().await.unwrap();
        apply_migrations(pool.clone(), APP_MIGRATIONS)
            .await
            .unwrap();
        let u = insert_user(&pool, "ada@x.com", "hash").await.unwrap();
        (pool, u.id)
    }

    #[tokio::test]
    async fn enroll_creates_pending_row() {
        let (pool, uid) = fresh().await;
        let row = enroll(&pool, &uid, "ABCDEF234567").await.unwrap();
        assert!(!row.enabled);
        assert!(row.confirmed_at.is_none());
        assert_eq!(row.secret_b32, "ABCDEF234567");
    }

    #[tokio::test]
    async fn confirm_flips_enabled_and_sets_confirmed_at() {
        let (pool, uid) = fresh().await;
        enroll(&pool, &uid, "SECRET").await.unwrap();
        let n = confirm_enabled(&pool, &uid).await.unwrap();
        assert_eq!(n, 1);
        let row = find(&pool, &uid).await.unwrap().unwrap();
        assert!(row.enabled);
        assert!(row.confirmed_at.is_some());
    }

    #[tokio::test]
    async fn confirm_is_idempotent_on_already_enabled() {
        let (pool, uid) = fresh().await;
        enroll(&pool, &uid, "SECRET").await.unwrap();
        confirm_enabled(&pool, &uid).await.unwrap();
        // Second confirm doesn't change anything (clause `enabled = 0`).
        assert_eq!(confirm_enabled(&pool, &uid).await.unwrap(), 0);
    }

    #[tokio::test]
    async fn enroll_again_resets_to_pending() {
        let (pool, uid) = fresh().await;
        enroll(&pool, &uid, "FIRST").await.unwrap();
        confirm_enabled(&pool, &uid).await.unwrap();
        // Re-enroll with a new secret -> pending again.
        let row = enroll(&pool, &uid, "SECOND").await.unwrap();
        assert!(!row.enabled);
        assert_eq!(row.secret_b32, "SECOND");
        let fetched = find(&pool, &uid).await.unwrap().unwrap();
        assert!(!fetched.enabled);
        assert!(fetched.confirmed_at.is_none());
    }

    #[tokio::test]
    async fn disable_removes_the_row() {
        let (pool, uid) = fresh().await;
        enroll(&pool, &uid, "SECRET").await.unwrap();
        let n = disable(&pool, &uid).await.unwrap();
        assert_eq!(n, 1);
        assert!(find(&pool, &uid).await.unwrap().is_none());
        // Re-disable is a no-op.
        assert_eq!(disable(&pool, &uid).await.unwrap(), 0);
    }
}
