//! Litestream config generation.
//!
//! Walks `data_dir` for every `*.db` file and emits a litestream YAML
//! that replicates each one to the configured S3 bucket. The remote
//! path under the bucket mirrors the file's path relative to
//! `data_dir`, so the on-disk layout is mirrored verbatim in the
//! bucket prefix.
//!
//! The set of DBs is fixed at generation time — adding a new realm or
//! app after `litestream.yml` was written requires regenerating + a
//! litestream restart. A future feature can automate that.

use crate::config::LitestreamConfig;
use anyhow::Result;
use std::fmt::Write;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct DbReplica {
    /// Absolute path to the SQLite file on disk.
    pub path: PathBuf,
    /// Path inside the bucket (already includes the `[litestream]` prefix).
    pub bucket_path: String,
}

/// Discover every `*.db` file under `data_dir` and pair it with the
/// bucket path it should sync to. Excludes WAL / SHM sidecars and any
/// existing `.db-journal` files.
pub fn discover_dbs(data_dir: &Path, prefix: Option<&str>) -> Result<Vec<DbReplica>> {
    let mut out = Vec::new();
    walk(data_dir, data_dir, prefix, &mut out)?;
    out.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(out)
}

fn walk(
    root: &Path,
    cur: &Path,
    prefix: Option<&str>,
    out: &mut Vec<DbReplica>,
) -> Result<()> {
    if !cur.exists() {
        return Ok(());
    }
    for entry in std::fs::read_dir(cur)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, prefix, out)?;
            continue;
        }
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if ext != "db" {
            continue;
        }
        let rel = path.strip_prefix(root).unwrap_or(&path);
        let rel_no_ext = rel.with_extension("");
        let key = rel_no_ext.to_string_lossy().replace('\\', "/");
        let bucket_path = match prefix {
            Some(p) if !p.is_empty() => format!("{}/{}", p.trim_end_matches('/'), key),
            _ => key,
        };
        out.push(DbReplica { path, bucket_path });
    }
    Ok(())
}

/// Render a litestream config covering every DB under `data_dir`.
pub fn render_yaml(data_dir: &Path, cfg: &LitestreamConfig) -> Result<String> {
    let dbs = discover_dbs(data_dir, cfg.prefix.as_deref())?;
    let bucket = cfg
        .bucket
        .as_deref()
        .ok_or_else(|| anyhow::anyhow!("litestream.bucket is not set"))?;
    let interval = cfg.replicate_interval_sec.max(1);

    let mut out = String::new();
    writeln!(out, "# Generated by RustBase. Do not edit by hand.").unwrap();
    writeln!(
        out,
        "# Sync interval: {interval}s. Adjust [litestream].replicate_interval_sec to change."
    )
    .unwrap();
    writeln!(out, "dbs:").unwrap();
    if dbs.is_empty() {
        writeln!(
            out,
            "  # no *.db files were present under {} at generation time",
            data_dir.display()
        )
        .unwrap();
    }
    for db in &dbs {
        writeln!(out, "  - path: {}", db.path.display()).unwrap();
        writeln!(out, "    replicas:").unwrap();
        writeln!(out, "      - type: s3").unwrap();
        writeln!(out, "        bucket: {bucket}").unwrap();
        writeln!(out, "        path: {}", db.bucket_path).unwrap();
        writeln!(out, "        sync-interval: {interval}s").unwrap();
    }
    Ok(out)
}

/// Write the generated YAML to `data_dir/litestream.yml`. Returns the
/// path written, suitable for logging.
pub async fn write_yaml(data_dir: &Path, cfg: &LitestreamConfig) -> Result<PathBuf> {
    let yaml = render_yaml(data_dir, cfg)?;
    let target = data_dir.join("litestream.yml");
    tokio::fs::write(&target, yaml).await?;
    Ok(target)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn cfg(bucket: &str, prefix: Option<&str>) -> LitestreamConfig {
        LitestreamConfig {
            enabled: true,
            bucket: Some(bucket.into()),
            prefix: prefix.map(str::to_string),
            replicate_interval_sec: 10,
        }
    }

    fn touch(dir: &Path, rel: &str) {
        let full = dir.join(rel);
        std::fs::create_dir_all(full.parent().unwrap()).unwrap();
        std::fs::write(&full, b"").unwrap();
    }

    #[test]
    fn discover_finds_all_db_files_recursively() {
        let dir = tempdir().unwrap();
        touch(dir.path(), "system.db");
        touch(dir.path(), "realms/acme/realm.db");
        touch(dir.path(), "realms/acme/apps/mobile/data.db");
        touch(dir.path(), "realms/acme/apps/mobile/data.db-wal");
        touch(dir.path(), "litestream.yml");

        let dbs = discover_dbs(dir.path(), None).unwrap();
        let names: Vec<_> = dbs.iter().map(|d| d.bucket_path.clone()).collect();
        assert!(names.contains(&"system".to_string()));
        assert!(names.contains(&"realms/acme/realm".to_string()));
        assert!(names.contains(&"realms/acme/apps/mobile/data".to_string()));
        // wal + yaml sidecars excluded
        assert_eq!(dbs.len(), 3);
    }

    #[test]
    fn prefix_is_prepended_to_bucket_path() {
        let dir = tempdir().unwrap();
        touch(dir.path(), "system.db");
        let dbs = discover_dbs(dir.path(), Some("prod")).unwrap();
        assert_eq!(dbs[0].bucket_path, "prod/system");
    }

    #[test]
    fn render_yaml_contains_all_entries() {
        let dir = tempdir().unwrap();
        touch(dir.path(), "system.db");
        touch(dir.path(), "realms/acme/realm.db");

        let yaml = render_yaml(dir.path(), &cfg("s3://my-bucket", Some("prod"))).unwrap();
        assert!(yaml.contains("dbs:"));
        assert!(yaml.contains("s3://my-bucket"));
        assert!(yaml.contains("path: prod/system"));
        assert!(yaml.contains("path: prod/realms/acme/realm"));
        assert!(yaml.contains("sync-interval: 10s"));
    }

    #[test]
    fn render_yaml_with_no_dbs_emits_placeholder_comment() {
        let dir = tempdir().unwrap();
        let yaml = render_yaml(dir.path(), &cfg("s3://b", None)).unwrap();
        assert!(yaml.contains("no *.db files"));
    }

    #[test]
    fn render_yaml_without_bucket_errors() {
        let dir = tempdir().unwrap();
        let lc = LitestreamConfig {
            enabled: true,
            bucket: None,
            ..Default::default()
        };
        assert!(render_yaml(dir.path(), &lc).is_err());
    }

    #[tokio::test]
    async fn write_yaml_creates_litestream_yml() {
        let dir = tempdir().unwrap();
        touch(dir.path(), "system.db");
        let path = write_yaml(dir.path(), &cfg("s3://b", None)).await.unwrap();
        assert_eq!(path, dir.path().join("litestream.yml"));
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("system"));
    }
}
