[package]
name = "rustbase-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "RustBaas server binary."

[[bin]]
name = "rustbase"
path = "src/main.rs"

[dependencies]
rustbase-api.workspace = true
rustbase-auth.workspace = true
rustbase-core.workspace = true
rustbase-db.workspace = true
rustbase-realtime.workspace = true
rustbase-runtime.workspace = true
rustbase-storage.workspace = true
tokio.workspace = true
axum.workspace = true
config.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
include_dir.workspace = true
mime_guess.workspace = true

[dev-dependencies]
tempfile = "3"
